### ISSUE TITLE
ISC ontology 

### ISSUE THREAD

**Issue by arademaker** [GeoscienceAustralia/geosciml.org#4]
File isc2018-1.ttl

```
# imports: https://raw.githubusercontent.com/ISO-TC211/GOM/master/isotc211_GOM_harmonizedOntology/19108/2006/iso19108TemporalReferenceSystem.rdf
```

Protege could not resolve this import statement.

**Comment by dr-shorthair** [comment]
It appears that the ISO Git repository was refactored on 18 May - https://github.com/ISO-TC211/GOM/commit/88768a6a2ee3dfb11fa86e40e1fa9c5e935dd7bb 

The ISO 19108 RDF is now at https://raw.githubusercontent.com/ISO-TC211/GOM/master/isotc211_GOM_harmonizedOntology/iso19108/2006/TemporalReferenceSystem.rdf

**Comment by dr-shorthair** [comment]
Now being mantained at https://github.com/CGI-IUGS/timescale-ont

**Comment by arademaker** [comment]
Let us close this issue here now. Any change can now be reported in https://github.com/dr-shorthair/timescale-ont.

**Comment by arademaker** [comment]
actually the repo is https://github.com/CGI-IUGS/timescale-ont

**Comment by KoalaGeo** [comment]
@dr-shorthair did you want to transfer the issues from here to https://github.com/CGI-IUGS/timescale-ont ....

**Comment by dr-shorthair** [comment]
You can only transfer issues automatically within a GitHub organization. 
I've copied-and-pasted the key content from #3 and #7 over to https://github.com/CGI-IUGS/timescale-ont/issues/1
