### ISSUE TITLE
Fork timescale components into a cleaner location(s)

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/geosciml.org#8]
The geologic timescale ontology and data are buried at the bottom of a long path (e.g. https://github.com/GeoscienceAustralia/geosciml.org/tree/master/resource/static/vocabulary/timescale) within a much larger set of topics in this repo. The directory structure is a legacy of an early hosting arrangement (at CSIRO), but now makes it more difficult than it should be to carry our focused conversations relating to both the structure and content. 

I suggest refactoring the code into to two new repositories
1. for the ontology
2. for the timescale data isc-2008 etc

Similar work could be done to refactor the other GeoSciML vocabularies into possibly several repos to organize the material thematically so that conversations are more discrete. I think the Git method (in order to preserve history) would be to fork the whole repo and then refactor in the new place. But (a) merging back to the original repo would not be automated in future (b) it would therefore no longer be consistent with the process for building the GeoSciML website which is partly automated using the existing paths. 

@nicholascar you might have comments here

**Comment by KoalaGeo** [comment]
I'd suggest not only new repo's but making a IUGS-CGI Organisation on GitHub ("IUGS-CGI" is currently available) for those repo's to sit in would also be appropriate rather than under GA.

**Comment by KoalaGeo** [comment]
Of course the geosciml.org repo could also be transferred to the new org for consistency.

**Comment by dr-shorthair** [comment]
@KoalaGeo I think you are at BGS. Can you represent the views of IUGS-CGI here? Of course we can fork there any time, but I would like to keep the current terminology maintainers @ollieraymond (GA) and @MarkRattenbury (NZ) in the loop and get their consent/blessing if possible (though I may be well out of date here). The current all-in-one-repo arrangement was inheritted from an earlier SVN system. Best Practice in code repositories has moved on since then, but this work has not kept up. @nicholascar (formerly at GA) in particular prefers to factor activities much more between many repositories and organizations, and I agree.

**Comment by arademaker** [comment]
I am glad we are considering restructuring the repository. Making the ontologies separated from the website code is a way to improve collaboration. I have already raised this issue in https://github.com/GeoscienceAustralia/geosciml.org/issues/3#issuecomment-528997823.

**Comment by dr-shorthair** [comment]
See https://github.com/dr-shorthair/timescale-ont and https://github.com/dr-shorthair/timescale-data - staging point pending https://github.com/CGI-IUGS being set up properly

**Comment by dr-shorthair** [comment]
addresses one of the things brought up in #7

**Comment by dr-shorthair** [comment]
Now moved to https://github.com/CGI-IUGS/timescale-data and https://github.com/CGI-IUGS/timescale-ont

**Comment by arademaker** [comment]
Not sure why the split of the instances (data) and the classes (ont) was necessary. But surely this was a huge improvement! Now we can contribute to those repositories instead to this one. But what about the files in https://github.com/GeoscienceAustralia/geosciml.org/tree/master/resource/static/ontology/timescale? Does it make sense to clean this repo now to avoid duplications and confusions?

**Comment by dr-shorthair** [comment]
Yes - in fact it is important to remove these sub-trees from here. I was just waiting on the GA and CGI people to tune in.

**Comment by KoalaGeo** [comment]
I'm happy with that...
